package ai.core.agent.formatter.formatters;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * @author stephen
 */
class DefaultCodeFormatterTest {
    DefaultCodeFormatter codeFormatter = new DefaultCodeFormatter();

    @Test
    void testFormat() {
        var code = """
                Code: `ls -l`
                """;

        var expected = "ls -l";

        var formattedCode = codeFormatter.formatter(code);

        Assertions.assertEquals(expected, formattedCode);
    }

    @Test
    void testFormat1() {
        var code = """
                ```java
                package ai.core.example;
                
                import ai.core.HuggingFaceModule;
                import ai.core.MultiAgentModule;
                import ai.core.lsp.LanguageServerModule;
                import core.framework.module.App;
                import core.framework.module.SystemModule;
                
                /**
                 * @author stephen
                 */
                public class ExampleApp extends App {
                    @Override
                    protected void initialize() {
                        load(new SystemModule("sys.properties"));
                        load(new MultiAgentModule());
                        load(new HuggingFaceModule());
                        load(new LanguageServerModule());
                        load(new ExampleModule());
                    }
                }
                ```
                """;

        var expected = """
                package ai.core.example;
                
                import ai.core.HuggingFaceModule;
                import ai.core.MultiAgentModule;
                import ai.core.lsp.LanguageServerModule;
                import core.framework.module.App;
                import core.framework.module.SystemModule;
                
                /**
                 * @author stephen
                 */
                public class ExampleApp extends App {
                    @Override
                    protected void initialize() {
                        load(new SystemModule("sys.properties"));
                        load(new MultiAgentModule());
                        load(new HuggingFaceModule());
                        load(new LanguageServerModule());
                        load(new ExampleModule());
                    }
                }""";

        var formattedCode = codeFormatter.formatter(code);

        Assertions.assertEquals(expected, formattedCode);
    }

    @Test
    void testFormat2() {
        var code = """
                ```python
                package ai.core.example;
                
                import ai.core.HuggingFaceModule;
                import ai.core.MultiAgentModule;
                import ai.core.lsp.LanguageServerModule;
                import core.framework.module.App;
                import core.framework.module.SystemModule;
                
                /**
                 * @author stephen
                 */
                public class ExampleApp extends App {
                    @Override
                    protected void initialize() {
                        load(new SystemModule("sys.properties"));
                        load(new MultiAgentModule());
                        load(new HuggingFaceModule());
                        load(new LanguageServerModule());
                        load(new ExampleModule());
                    }
                }
                """;

        var expected = """
                package ai.core.example;
                
                import ai.core.HuggingFaceModule;
                import ai.core.MultiAgentModule;
                import ai.core.lsp.LanguageServerModule;
                import core.framework.module.App;
                import core.framework.module.SystemModule;
                
                /**
                 * @author stephen
                 */
                public class ExampleApp extends App {
                    @Override
                    protected void initialize() {
                        load(new SystemModule("sys.properties"));
                        load(new MultiAgentModule());
                        load(new HuggingFaceModule());
                        load(new LanguageServerModule());
                        load(new ExampleModule());
                    }
                }""";

        var formattedCode = codeFormatter.formatter(code);

        Assertions.assertEquals(expected, formattedCode);
    }

    @Test
    void testFormat3() {
        var code = """
                Code generated by ChatGPT:
                ```python
                package ai.core.example;
                
                import ai.core.HuggingFaceModule;
                import ai.core.MultiAgentModule;
                import ai.core.lsp.LanguageServerModule;
                import core.framework.module.App;
                import core.framework.module.SystemModule;
                
                /**
                 * @author stephen
                 */
                public class ExampleApp extends App {
                    @Override
                    protected void initialize() {
                        load(new SystemModule("sys.properties"));
                        load(new MultiAgentModule());
                        load(new HuggingFaceModule());
                        load(new LanguageServerModule());
                        load(new ExampleModule());
                    }
                }
                ```
                Explanation:
                bala bala
                """;

        var expected = """
                package ai.core.example;
                
                import ai.core.HuggingFaceModule;
                import ai.core.MultiAgentModule;
                import ai.core.lsp.LanguageServerModule;
                import core.framework.module.App;
                import core.framework.module.SystemModule;
                
                /**
                 * @author stephen
                 */
                public class ExampleApp extends App {
                    @Override
                    protected void initialize() {
                        load(new SystemModule("sys.properties"));
                        load(new MultiAgentModule());
                        load(new HuggingFaceModule());
                        load(new LanguageServerModule());
                        load(new ExampleModule());
                    }
                }""";

        var formattedCode = codeFormatter.formatter(code);

        Assertions.assertEquals(expected, formattedCode);
    }
}