package ai.core.server.domain;

import core.framework.api.validate.NotNull;
import core.framework.mongo.Collection;
import core.framework.mongo.Field;
import core.framework.mongo.Id;

import java.time.ZonedDateTime;

/**
 * Subject (business subject under a project): the stable anchor of KPI/report series
 * (product decision D5 — an entity, not free text, so LLM-written names cannot fragment series).
 *
 * @author stephen
 */
@Collection(name = "project_subjects")
public class ProjectSubject {
    @Id
    public String id;

    @NotNull
    @Field(name = "project_id")
    public String projectId;

    @NotNull
    @Field(name = "user_id")
    public String userId;   // copied from the project on create; list queries avoid the join

    @NotNull
    @Field(name = "name")
    public String name;

    @Field(name = "description")
    public String description;

    @Field(name = "external_link")
    public String externalLink;

    // started (default, null = started) = included in scheduled analysis; paused = skipped by
    // scheduled runs only (manual subject-level Analyze now still works)
    @Field(name = "status")
    public String status;

    // stable facts about the subject (JSON object text), extracted by the subject analyzer,
    // overwritten per analysis
    @Field(name = "profile")
    public String profile;

    // subject-level analysis cursor: attributed material older than this has been analyzed
    // by the subject-analysis stage; failures leave it untouched so the next run retries
    @Field(name = "analyzed_at")
    public ZonedDateTime analyzedAt;

    // ---- HTML campaign report (v1.4, generated by the project-report-renderer) ----
    // the report is subject-level: KPI series only make sense within one subject (D5)
    @Field(name = "report_file_id")
    public String reportFileId;            // latest report artifact

    @Field(name = "report_share_token")
    public String reportShareToken;        // share token for the iframe src

    @Field(name = "report_generated_at")
    public ZonedDateTime reportGeneratedAt;

    @Field(name = "report_error")
    public String reportError;             // last failed render message

    @Field(name = "report_events_at")
    public ZonedDateTime reportEventsAt;   // watermark: events newer than this need a re-render

    // in-flight render state (the renderer is an agent run, completed by ProjectReportCompletionJob)
    @Field(name = "report_run_id")
    public String reportRunId;             // the agent run id, polled to detect completion

    @Field(name = "report_draft_id")
    public String reportDraftId;           // the draft doc the agent appends sections to

    @NotNull
    @Field(name = "created_at")
    public ZonedDateTime createdAt;

    @NotNull
    @Field(name = "updated_at")
    public ZonedDateTime updatedAt;
}
