package ai.core.server.domain;

import core.framework.api.validate.NotNull;
import core.framework.mongo.Collection;
import core.framework.mongo.Field;
import core.framework.mongo.Id;

import java.time.ZonedDateTime;
import java.util.List;

/**
 * Subject (business subject under a project): the stable anchor of KPI/report series
 * (product decision D5 — an entity, not free text, so LLM-written names cannot fragment series)
 * and the ONLY carrier of current state: phase/summary and the action-item list live here, the
 * history behind them in {@link ProjectSubjectEvent}.
 *
 * @author stephen
 */
@Collection(name = "project_subjects")
public class ProjectSubject {
    @Id
    public String id;

    @NotNull
    @Field(name = "project_id")
    public String projectId;

    @NotNull
    @Field(name = "user_id")
    public String userId;   // copied from the project on create; list queries avoid the join

    @NotNull
    @Field(name = "name")
    public String name;

    @Field(name = "description")
    public String description;

    @Field(name = "external_link")
    public String externalLink;

    // started (default, null = started) = included in scheduled analysis; paused = skipped by
    // scheduled runs only (manual subject-level Analyze now still works)
    @Field(name = "status")
    public String status;

    // manual (default, null = manual) | auto — auto rows are created by the attribution stage
    @Field(name = "source")
    public String source;

    // normalized name of auto-created subjects only: backs the partial unique index
    // (project_id, name_key) with source=auto, manual subjects are not constrained
    @Field(name = "name_key")
    public String nameKey;

    // why the attributor proposed this subject (shown on the review bar)
    @Field(name = "proposal_reason")
    public String proposalReason;

    @Field(name = "proposed_at")
    public ZonedDateTime proposedAt;

    // stable facts about the subject (JSON object text), extracted by the subject analyzer,
    // overwritten per analysis
    @Field(name = "profile")
    public String profile;

    // ---- current state (overwrite semantics; every change appends a history event) ----
    @Field(name = "phase")
    public String phase;

    @Field(name = "summary")
    public String summary;

    @Field(name = "status_updated_at")
    public ZonedDateTime statusUpdatedAt;   // material time of the current phase/summary

    @Field(name = "status_updated_by")
    public String statusUpdatedBy;

    @Field(name = "action_items")
    public List<ProjectActionItem> actionItems;

    // subject-level analysis cursor: attributed material older than this has been analyzed
    // by the subject-analysis stage; failures leave it untouched so the next run retries
    @Field(name = "analyzed_at")
    public ZonedDateTime analyzedAt;

    // ---- HTML campaign report (v1.4, generated by the project-report-renderer) ----
    // the report is subject-level: KPI series only make sense within one subject (D5)
    @Field(name = "report_file_id")
    public String reportFileId;            // latest report artifact

    @Field(name = "report_share_token")
    public String reportShareToken;        // share token for the iframe src

    @Field(name = "report_generated_at")
    public ZonedDateTime reportGeneratedAt;

    @Field(name = "report_error")
    public String reportError;             // last failed render message

    @Field(name = "report_events_at")
    public ZonedDateTime reportEventsAt;   // watermark: events newer than this need a re-render

    // in-flight render state (the renderer is an agent run, completed by ProjectReportCompletionJob)
    @Field(name = "report_run_id")
    public String reportRunId;             // the agent run id, polled to detect completion

    @Field(name = "report_draft_id")
    public String reportDraftId;           // the draft doc the agent appends sections to

    @NotNull
    @Field(name = "created_at")
    public ZonedDateTime createdAt;

    @NotNull
    @Field(name = "updated_at")
    public ZonedDateTime updatedAt;
}
